INFO     root:Log.py:79 [INFO 2019-11-03 22:13:26]初始化关联文件
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 22:13:26]读取初始关联文件内容：   ItemsView(<Section: test_data>)
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 22:13:26]初始关联内容数据处理后：   {'name': '7', 'type': 'Web', 'version': 'dhmsS2qV7L', 'description': 'api_auto_Vj2htUsZfu', 'project_id': 'c9aad29894b84640927e9765b528e0e1', 'token_id': '978b3893ad1a41029450d084b154a80d', 'project_name': '4wCIy3iDLN0BHaxenPj5', 'network_name': 'tYyizfG0gA4u2KNlDFHQ_netwrok', 'subnet_name': '4UF2yivQ6otkqGV7HRTY_subnet', 'network_id': '5ee5980c-bd4e-4864-96f0-efa887e9effa', 'subnet_id': '73d89c4e-e09d-4142-8015-751fe8bcc97c', 'image_id': '39c5aa0b-66b1-4871-a7d4-62ab6ceee946', 'flavor_id': 'flavor-1-1-1', 'server_name': 'wuzs_FHDEkXKG8Peo3RZivMQJ', 'server_id': 'dbeef329-c3d8-40b5-a7ce-d3315acc102f', 'project_token_name': 'LrFyQgel3zSGEapDPj71', 'admin_id': 'f42a1487dd4e4a6baab6eb65f50f8db0', 'admin_role_id': 'f8d49cf5c0d74f7b85c462219b300f78', 'volume_name': 'volume_7lD9TXCUvLbzxQtVepG5', 'volume_id': '857d1f3b-1d27-4873-803c-a6ebbeadfd1b', 'server_snap_name': 'snap_8JkrX4yjSduLBPHcmTxC', 'server_snap_id': '', 'volume_snapshot_id': '38b5852e-c20d-41c8-a623-fac063c92dc2', 'network_name_for_check': 'fMQr7ph3ancyb4GPSdDu_netwrok'}
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]====================================================================================================
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 22:13:28]请求头处理结果：  {'Content-Type': 'application/json', 'X-Auth-Token': '978b3893ad1a41029450d084b154a80d'}
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 22:13:28]请求参数处理结果：  {'Content-Type': 'application/json', 'X-Auth-Token': '978b3893ad1a41029450d084b154a80d'}
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 22:13:28]host处理结果：  192.168.54.103
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]请求接口：删除网络后查看网络
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]请求地址：http://192.168.54.103:9696/v2.0/networks/5ee5980c-bd4e-4864-96f0-efa887e9effa
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]请求头: {'Content-Type': 'application/json', 'X-Auth-Token': '978b3893ad1a41029450d084b154a80d'}
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]请求参数: {'subnet': {'admin_state_up': True}}
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]GET请求接口
DEBUG    urllib3.connectionpool:connectionpool.py:205 Starting new HTTP connection (1): 192.168.54.103:9696
DEBUG    urllib3.connectionpool:connectionpool.py:393 http://192.168.54.103:9696 "GET /v2.0/networks/5ee5980c-bd4e-4864-96f0-efa887e9effa?subnet=admin_state_up HTTP/1.1" 404 137
INFO     root:Log.py:79 [INFO 2019-11-03 22:13:28]接口请求结果：
                         (404, {'NeutronError': {'message': 'Network 5ee5980c-bd4e-4864-96f0-efa887e9effa could not be found', 'type': 'NetworkNotFound', 'detail': ''}})