INFO     root:Log.py:79 [INFO 2019-11-03 20:32:18]初始化关联文件
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 20:32:18]读取初始关联文件内容：   ItemsView(<Section: test_data>)
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 20:32:18]初始关联内容数据处理后：   {'name': '9', 'type': 'Web', 'version': 'PNZcAvmLl8', 'description': 'api_auto_SU8H5TnQWv', 'project_id': '72695eb0907c49a8bdc61419202f93f0', 'token_id': '5c5f4245409f4092975490870bd37ad8', 'project_name': 'QX5Nb32FsVIjG67mzkMe', 'network_name': 'VvsYbMujW1apS3C7IGLg_netwrok', 'subnet_name': 'xmu8IgT9Ow0XYkr2KoFt_subnet', 'network_id': 'e230d4e4-3cad-4388-9530-6121c7ff8d12', 'subnet_id': 'd4dacc66-ae0f-4b86-87a2-ede584a80d3b', 'image_id': 'b4e9e907-686e-440d-bc1a-d73a8decfa54', 'flavor_id': 'flavor-1-1-1', 'server_name': 'wuzs_GoXesZiwbJ0pzmdBk2fM', 'server_id': 'd1a9af77-3a5e-406d-b073-9c5297cebdb5', 'project_token_name': 'Fts5kgWa6R7h4B8XLZSE', 'admin_id': '0ec82b7380cb4d0c80058501938cdf48', 'admin_role_id': 'cc33f2c3a47247329d0ee7043c4f475f', 'volume_name': 'volume_GKOrFlEAqN2jJmbe8wop', 'volume_id': '2de7c20e-f75e-45fa-aad4-47586902619b', 'server_snap_name': 'snap_8JkrX4yjSduLBPHcmTxC', 'server_snap_id': '', 'volume_snapshot_id': 'ba54bdde-8dc1-49dd-8352-ff87355714cd', 'network_name_for_check': '2n8bMgjXy7modiqBZrTY_netwrok'}
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]====================================================================================================
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 20:32:20]请求头处理结果：  {'Content-Type': 'application/json', 'X-Auth-Token': '5c5f4245409f4092975490870bd37ad8'}
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 20:32:20]请求参数处理结果：  {'Content-Type': 'application/json', 'X-Auth-Token': '5c5f4245409f4092975490870bd37ad8'}
DEBUG    root:Log.py:73 [DEBUG 2019-11-03 20:32:20]host处理结果：  192.168.54.120
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]请求接口：删除网络后查看网络
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]请求地址：http://192.168.54.120:9696/v2.0/networks/e230d4e4-3cad-4388-9530-6121c7ff8d12
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]请求头: {'Content-Type': 'application/json', 'X-Auth-Token': '5c5f4245409f4092975490870bd37ad8'}
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]请求参数: {'subnet': {'admin_state_up': True}}
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]GET请求接口
DEBUG    urllib3.connectionpool:connectionpool.py:205 Starting new HTTP connection (1): 192.168.54.120:9696
DEBUG    urllib3.connectionpool:connectionpool.py:393 http://192.168.54.120:9696 "GET /v2.0/networks/e230d4e4-3cad-4388-9530-6121c7ff8d12?subnet=admin_state_up HTTP/1.1" 404 137
INFO     root:Log.py:79 [INFO 2019-11-03 20:32:20]接口请求结果：
                         (404, {'NeutronError': {'message': 'Network e230d4e4-3cad-4388-9530-6121c7ff8d12 could not be found', 'type': 'NetworkNotFound', 'detail': ''}})